-- ============================================================================
-- project_knowledge inserts — 2026-08-07 finance documentation & governance
-- Channel rule: docs/AI_MEMORY.md is AUTO-GENERATED by knowledgeReview.ts from
-- the project_knowledge table every 24h. NEVER hand-edit docs/AI_MEMORY.md — insert
-- rows here and they appear in AI_MEMORY at the next heartbeat.
--
-- Run against the beta DB:
--   mysql -h 35.245.41.148 -u geeves_app -p geeves_beta < project_knowledge_inserts_20260807.sql
-- Idempotent: each block deletes its (category,key) before inserting.
-- ============================================================================

-- ── Governance ──────────────────────────────────────────────────────────────
DELETE FROM project_knowledge WHERE category='governance' AND `key`='document_governance_rule';
INSERT INTO project_knowledge (category, `key`, value, sourceDoc, notes, lastReviewedAt) VALUES
('governance','document_governance_rule',
 'ALL project documents and plans MUST be pushed to the repo (TJP-GLOBAL-GROUP/geeves-life): plans under docs/, finance workpapers under docs/finance/. After every key document update or completed review, knowledge updates are inserted into the project_knowledge DB table (NEVER hand-edit docs/AI_MEMORY.md — it is auto-generated by knowledgeReview.ts from project_knowledge every 24h and hand edits are wiped). Session/agent-generated artifacts must never remain workspace-only.',
 'Owner directive 2026-08-07, mechanic correction same date',
 'Owner directive; updated with the project_knowledge channel mechanic', NOW());

-- ── Finance document set ────────────────────────────────────────────────────
DELETE FROM project_knowledge WHERE category='finance' AND `key` IN ('plan_v2_1_location','plan_companion_artifacts','manus_review_v2_1','plan_v2_2_status');
INSERT INTO project_knowledge (category, `key`, value, sourceDoc, notes, lastReviewedAt) VALUES
('finance','plan_v2_1_location',
 'Canonical finance plan v2.1 lives at docs/Geeves_Unified_Finance_Implementation_Plan_v2.1.md (swarm-reviewed, decisions D1-D6 locked). The "Draft 1 (July 29)" reviewed in docs/FINANCE_PLAN_REVIEW.md is a DIFFERENT, superseded document — do not confuse them.',
 'docs/Geeves_Unified_Finance_Implementation_Plan_v2.1.md', NULL, NOW()),
('finance','plan_companion_artifacts',
 'Companions under docs/finance/: migration_pack.sql (SQLite STAGING cleanup pack — idempotent, validated 2x on a staging copy; provisions NO production schema; NEVER run against the original DB), VERTICAL_GL_CATALOGS_v2.md (post-migration chart of accounts, 139 rows), uiux_review_g6_report.md (round-1 G6 review; role matrix defect: EA bucketed read-only — superseded by Manus Part 3 access model + pending brand redo).',
 'docs/finance/', NULL, NOW()),
('finance','manus_review_v2_1',
 'Manus pre-implementation review of the CORRECT v2.1: docs/FINANCE_PLAN_REVIEW_V2.1.md (code-verified vs schema.ts/rbac.ts/db.ts). Verdict: accounting endorsed intact; v2.1 not implementable without 6 deltas (production Drizzle migration, CoA convergence, vertical identity bridge, household scope decision, Part 3 access model, Square non-goal). Includes Phase 0 gate (0.1-0.9) + Phases A-F accountability checklist.',
 'docs/FINANCE_PLAN_REVIEW_V2.1.md', NULL, NOW()),
('finance','plan_v2_2_status',
 'Plan v2.2 = v2.1 accounting (unchanged: precedence matrix, 4-class dedupe, interest retype, decomposed anchors, PII scrub) + production Drizzle migration + chart_of_accounts canonical (D8) + verticals.code bridge + single-household ledger under tarik@tjperkinsfam.com / TJ Perkins Global (D7) + Part 3 access model (D9 approved) + G2 materiality floor $50 with 90-day suspense review (D10) + Square explicit non-goal. Integration brief: docs/finance/FINAL_NOTES_v2.2_Integration_Brief.md.',
 'docs/finance/FINAL_NOTES_v2.2_Integration_Brief.md', NULL, NOW());

-- ── Locked decisions D1-D10 ─────────────────────────────────────────────────
DELETE FROM project_knowledge WHERE category='finance_decisions';
INSERT INTO project_knowledge (category, `key`, value, sourceDoc, notes, lastReviewedAt) VALUES
('finance_decisions','D1_self_fold','SELF vertical eliminated, maps into PERS. Zero DB rows — doc-side fold only. Post-fold spend non-deductible (Form 2106/Sch A suspended through TY2025).','Plan v2.1 §0',NULL,NOW()),
('finance_decisions','D2_codes_canonical','Staging vertical codes (MB/MM/BL/PERS/FAM/GL/SO/BLab/TJPGG + REV/MULTI) canonical; staging 3-digit account codes are system of record; doc 4-digit codes retired to vertical_code_map.doc_code.','Plan v2.1 §0',NULL,NOW()),
('finance_decisions','D3_gl_collision','Staging GL = Geeves.Life keeps the code; doc "Good Life" renamed GDL (zero data).','Plan v2.1 §0',NULL,NOW()),
('finance_decisions','D4_fiscal_month','month = fiscal calendar month from date for ALL rows; 119 Scotia statement-cycle mismatches collapsed with per-row old-value logging. Nothing compares against Scotia statements.','Plan v2.1 §0','Resolved 2026-08-07',NOW()),
('finance_decisions','D5_mirror_currency','The 2 NULL-currency owner_journal mirror rows (20057/20058) are USD.','Plan v2.1 §0','Resolved 2026-08-07',NOW()),
('finance_decisions','D6_realm_allowlist','2 QBO realms on the sync allowlist (bakery 123145971566304, MMG 9130350512376806); may expand later. All other verticals geeves_only but QBO-export-ready. PERS/FAM hard-excluded. Enforced by data via vertical_code_map.sync_allowlisted.','Plan v2.1 §0','Resolved 2026-08-07',NOW()),
('finance_decisions','D7_ledger_scope','Single household layer: the ledger belongs to the household owned by tarik@tjperkinsfam.com (TJ Perkins Global, V8lk3KJatvxBTWURf4uo9). MB/MM verticals migrate into it from TJ Perkins Fam. householdId is the top-level scope key.','Owner decision 2026-08-07','Resolves Manus CRITICAL-4',NOW()),
('finance_decisions','D8_coa_naming','chart_of_accounts is the canonical production account table (already QBO-bound via coa_mappings). Staging gl_accounts is an import source only. Tax-form dimension: journal_lines columns override account defaults (line-overrides-account precedence, documented). journal_lines.glAccountId gets a real FK to chart_of_accounts.','Owner decision 2026-08-07','Resolves Manus CRITICAL-2',NOW()),
('finance_decisions','D9_access_model','Manus Part 3 access model approved: vertical co-admin = vertical_owners.isFinancialOwner; 5 vertical-scoped capabilities (view_aggregate/view_detail/post/resolve_workbench/export_qbo) + 2 global (assign_vertical, view_sensitive); single fail-closed resolver canAccessFinancials() called FIRST in every financial procedure; EA gets mutating rights on assigned verticals but NOT the Unassigned queue; QBO export household-admin-only; cross-vertical redaction via shadow_blocks/busyLabel pattern; vertical-in-URL routing /finance/:verticalCode/...','Owner decision 2026-08-07','Resolves Manus CRITICAL-5/6; fixes G6 EA defect',NOW()),
('finance_decisions','D10_g2_materiality','Gate G2 softened from strict-zero to materiality: zero unresolved items above $50, zero in owner-judgement conflict classes (65 dedupe + 17 H5 + contested overlaps), documented residual below floor parked in suspense with named owner (Tarik) and 90-day review date.','Owner decision 2026-08-07','Resolves Manus HIGH-1',NOW()),
('finance_decisions','square_non_goal','Square is an EXPLICIT NON-GOAL (owner decision 2026-08-07): no connector, no settlement parsing, no rail enum value, no CoA seed. If ever in scope, reuse the Stripe merchant-clearing pattern (gross income, contra-revenue refunds, fee expense, net payout as asset transfer).','Owner decision 2026-08-07','Recorded in Manus v2.1 review scope boundary',NOW());

-- ── Security & accounting positions (do not regress) ────────────────────────
DELETE FROM project_knowledge WHERE category='finance_security';
INSERT INTO project_knowledge (category, `key`, value, sourceDoc, notes, lastReviewedAt) VALUES
('finance_security','beneficiary_sidecar','beneficiary_tags (child PII) stays a SIDECAR table — NEVER in journal_lines, QBO payloads, exports, audit metadata, or logs. Category subtotals can equal single sensitive lines (aggregate=line leak, $17,399.36) so k-anonymity suppression is computed at query time (line count < 3), never a static denylist.','Plan v2.1 §5 / Manus E7,B13',NULL,NOW()),
('finance_security','pii_scrub_before_mapping','Child-identifying category names scrubbed to neutral labels (FAM — Medical/Therapy, FAM — Medical Travel) BEFORE any gl_category_map rows are written; denylist lint on all QBO-visible strings.','migration_pack.sql §7',NULL,NOW()),
('finance_security','migration_discipline','Migration scripts: snapshot per batch, dry-run + explicit --apply, same-transaction change logging, IDs+hashes only (no raw descriptions/names/amounts), least-privilege migration role != app runtime role, per-batch post-commit validation.','migration_pack.sql header',NULL,NOW()),
('finance_security','interest_is_expense','Interest is card-charge EXPENSE ($30,738.29 raw; income only $2.80). Four routing targets retyped money_in -> money_out (MB-420/MM-420/BL-420/TJP-410). Rollup covers only ~42% of raw charges — owner to explain uncovered cards (e.g. amex_biz $15,187.22 vs $9,021.47).','Plan v2.1 §3.5',NULL,NOW()),
('finance_security','rails_never_swallow_revenue','Precedence matrix: rail wins only when disposition=rail; income on a paired txn = REVIEW item (mis-paired deposit), never a rail; equity posts equity-leg-only reconciled against transfer_pairs; refunds post same-account contra, never rail.','Plan v2.1 §3.4','Manus: "single most valuable sentence in the document"',NOW()),
('finance_security','mb_jamaican_ltd','Maxfield Bakery is an 83%-owned Jamaican Ltd — NOT Schedule C. Jamaican corporate return + GCT for the Ltd; Form 5471/CFC/GILTI for the US owner. Jamaica PAYE/NIS/NHT/EdTax/HEART on director''s emoluments.','Plan v2.1 §5',NULL,NOW()),
('finance_security','infra_already_done','OAuth hardening DONE (commits 53f626c/38a46d8); Cloud SQL cutover RESOLVED (TiDB removed). Production already has: propertyId on journal tables, airbnb_payout_records (gross/hostFee/taxes/netPayout decomposition), property_bookings.commissionAmount, exchange_rates table, journal line currency/exchangeRate/usdEquivalent. Phase 5 property work = JOIN not build.','Manus v2.1 review HIGH-4/HIGH-7',NULL,NOW());

-- POST: row counts by category.
-- EXPECT: governance=1, finance=4, finance_decisions=11, finance_security=7
SELECT category, COUNT(*) AS rows_seeded FROM project_knowledge
 WHERE category IN ('governance','finance','finance_decisions','finance_security')
 GROUP BY category;
