export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  systemCronSecret: process.env.SYSTEM_CRON_SECRET ?? "",
  gcsBucketName: process.env.GCS_BUCKET_NAME ?? "",
  googleCredentialsJson: process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON ?? "",
  shadowBlockEngineEnabled: process.env.SHADOW_BLOCK_ENGINE_ENABLED !== "false",
  enableWebhookTokenCheck: process.env.ENABLE_WEBHOOK_TOKEN_CHECK === "true",
  guardianEnabled: process.env.GUARDIAN_ENABLED !== "false",
  guardianAutoFix: process.env.GUARDIAN_AUTO_FIX !== "false",
  guardianAlertEmail: process.env.GUARDIAN_ALERT_EMAIL ?? "tarik@tjperkinsfam.com",
  guardianEmergencyPhone: process.env.GUARDIAN_EMERGENCY_PHONE ?? "",
};
